services:

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Niki
      POSTGRES_DB: task_queue_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_queue_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Niki@postgres:5432/task_queue_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - uploads_data:/app/uploads
      - converted_data:/app/converted
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    command: python worker.py
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Niki@postgres:5432/task_queue_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - uploads_data:/app/uploads
      - converted_data:/app/converted
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:
  uploads_data:
  converted_data:

networks:
  app_network:
    driver: bridge